### ISSUE TITLE
Error while syncing tracking data to PayPal -> Sync GZD Tracking (1015)

### ISSUE THREAD

**Issue by wolkenkrieger** [woocommerce/woocommerce-paypal-payments#1020]
Since the update to 2.0.0 the following errors occured while saving/changing the status of an order (to "processed"):

1. Couldn’t sync tracking information: [INVALID_TRACKER_ID] Invalid data provided
2. Couldn’t sync tracking information: [Number of Updates More than Permissible] The requested resource ID was not found

I use the plugin "Germanized for Woocommerce" and the Shipping Carrier is Deutsche Post DHL. The Tracking ID is synced to PayPal (what, for me, is the opposite of error 1?!) but the the order will remain unshipped for PayPal.

This eoor blocks the sending of the "Order is shipped"-Mail to the customer (the coder of "Germanized" is informed, too).

**Comment by wolkenkrieger** [comment]
[Additional]

printed $exception:

```
WooCommerce\PayPalCommerce\ApiClient\Exception\PayPalApiException Object
(
    [message:protected] => [Number of Updates More than Permissible] The requested resource ID was not found
    [string:Exception:private] => 
    [code:protected] => 400
    [file:protected] => /home/wc/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-order-tracking/src/Endpoint/OrderTrackingEndpoint.php
    [line:protected] => 289
    [trace:Exception:private] => Array
        (
            [0] => Array
                (
                    [file] => /home/wc/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-compat/src/CompatModule.php
                    [line] => 176
                    [function] => update_tracking_information
                    [class] => WooCommerce\PayPalCommerce\OrderTracking\Endpoint\OrderTrackingEndpoint
                    [type] => ->
                )

            [1] => Array
                (
                    [file] => /home/wc/wp-includes/class-wp-hook.php
                    [line] => 310
                    [function] => WooCommerce\PayPalCommerce\Compat\{closure}
                    [class] => WooCommerce\PayPalCommerce\Compat\CompatModule
                    [type] => ::
                )

            [2] => Array
                (
                    [file] => /home/wc/wp-includes/class-wp-hook.php
                    [line] => 332
                    [function] => apply_filters
                    [class] => WP_Hook
                    [type] => ->
                )

            [3] => Array
                (
                    [file] => /home/wc/wp-includes/plugin.php
                    [line] => 517
                    [function] => do_action
                    [class] => WP_Hook
                    [type] => ->
                )

            [4] => Array
                (
                    [file] => /home/wc/wp-content/plugins/woocommerce-germanized/packages/woocommerce-germanized-shipments/src/Shipment.php
                    [line] => 2753
                    [function] => do_action
                )

[...]
```

**Comment by wolkenkrieger** [comment]
Quickfix in functions.php:

`add_filter( 'woocommerce_paypal_payments_sync_gzd_tracking', '__return_false' );`


**But!! This is critical!**

With this quickfix NO shipping data will synced to PayPal!! You have to enter the shipping data manually with PayPal in order to retain seller protection.

**Comment by dennisnissle** [comment]
The issue is that the exception caught is actually being thrown [here](https://github.com/woocommerce/woocommerce-paypal-payments/blob/f6802dd9770c4bdb46ac0fd93072f840820a1c4a/modules/ppcp-compat/src/CompatModule.php#L180). That will lead to not firing the actual status transition for the shipment save event.

This needs to be fixed please.

**Comment by wolkenkrieger** [comment]
And only on update_ ... add_ ist working so far

**Comment by Dinamiko** [comment]
Hi @wolkenkrieger, I've just merged @dennisnissle PR and attaching the package here, will be great if you can give it a try to ensure it fixes the issue, thanks in advance.
[woocommerce-paypal-payments.zip](https://github.com/woocommerce/woocommerce-paypal-payments/files/10112389/woocommerce-paypal-payments.zip)

**Comment by wolkenkrieger** [comment]
No, it can't fix the issue!

Have a look at https://github.com/woocommerce/woocommerce-paypal-payments/blob/trunk/modules/ppcp-order-tracking/src/Endpoint/OrderTrackingEndpoint.php

the functions add_tracking_information() and update_tracking_information() still throw exceptions, which remains unhandled!

**Comment by dennisnissle** [comment]
@wolkenkrieger - no it can't as the part is wrapped in a try/catch:
https://github.com/dennisnissle/woocommerce-paypal-payments/blob/65b5b829fe296faac1226b98f58fbf3cfede9b1f/modules/ppcp-compat/src/CompatModule.php#L177

Cheers

**Comment by wolkenkrieger** [comment]
Holy sh*t, ur right :) *mea culpa*

I will give it a try asap :)

**Comment by wolkenkrieger** [comment]
Ok, the exception did not break the function chain any more ... but the real problem persists:

```
2022-11-29T12:38:24+00:00 DEBUG PUT https://api.paypal.com/v1/shipping/trackers/6JJ7619XXX9905H-00340XXX3764300294
Request Body: {"transaction_id":"6JJ7XXXX209905H","status":"SHIPPED","tracking_number":"003XXXX623764300294","carrier":"DHL_DEUTSCHE_POST"}
Response Debug ID: a79713ddf5cb5
Response: Array
(
    [code] => 400
    [message] => Bad Request
)

Response Body: {"name":"Number of Updates More than Permissible","message":"The requested resource ID was not found","debug_id":"a79713ddf5cb5","details":[{"field":"tracker_id","value":"Number of Updates More than Permissible","location":"path","issue":"Number of Updates More than Permissible"}],"links":[]}

2022-11-29T12:38:24+00:00 WARNING Failed to update the order tracking information. PayPal API response: [Number of Updates More than Permissible] The requested resource ID was not found
```

**Comment by Dinamiko** [comment]
@wolkenkrieger `Number of Updates More than Permissible` seems a limitation on PayPal side, probably it doesn’t allow you to update tracking more than certain number of times.

Let us confirm it and see if we can find a way to handle it, in the meantime can you please try changing the tracking number to see if the issue persist or not? thanks.

**Comment by wolkenkrieger** [comment]
> in the meantime can you please try changing the tracking number to see if the issue persist or not?

You know this is a production webshop, right?

**Comment by Dinamiko** [comment]
> You know this is a production webshop, right?

sorry for that, I was thinking you were in a staging site.

I've just checked and confirming it throws the error on the fifteenth call on this same update endpoint:
```
PUT https://api.sandbox.paypal.com/v1/shipping/trackers/53J0677063752803F-1234
{"transaction_id":"53J0677063752803F","status":"SHIPPED","tracking_number":"1234","carrier":"DHL_DEUTSCHE_POST"}
```

When changing the status of Germanized shipment then we automatically send the tracking info to PayPal, let see if we can improve that to reduce the number of calls somehow.

**Comment by dennisnissle** [comment]
@Dinamiko - you should only send the API call in case the tracking id has actually changed :)

**Comment by wolkenkrieger** [comment]
> you should only send the API call in case the tracking id has actually changed

And / orr if the status changed from "ON_HOLD" to "SHIPPED"

For PUI this is mandatory! Otherwise the seller will get no seller protection!

**Comment by Dinamiko** [comment]
> you should only send the API call in case the tracking id has actually changed :)

@dennisnissle what about when status or carriers are updated on Germanized side?

We currently call PayPal tracking API update endpoint everytime one of these (tracking id, status or carrier) are updated, we tried to sent only the ones that are changed, but it does not affect the limitation, as soon as 15 calls are done it throws the error no matter the number of parameters in the payload sent.

**Comment by dennisnissle** [comment]
@Dinamiko I was talking about the tracking id managed within the shipment data which is transferred to PayPal. I guess it makes sense to only transmit data to PayPal whenever the tracking id changes (e.g. is set). This should normally not happen more than a few times (normally only once). 

You could use the `woocommerce_gzd_shipment_status_shipped` hook (use a high hook priority, e.g. 500 to make sure to fire after certain automation events) instead of the `woocommerce_gzd_shipment_after_save` hook to only update the data whenever a shipment is marked as shipped. See: https://github.com/vendidero/woocommerce-germanized-shipments/blob/master/src/Shipment.php#L2142

**Comment by Dinamiko** [comment]
@dennisnissle #1050 PR ready to be merged, it looks good to me, will be great if you can take a look before merging, thanks in advance.

**Comment by dennisnissle** [comment]
@Dinamiko Looks good to me too!
