### ISSUE TITLE
Fatal crash on update to 2.7.1 undefined function WooCommerce\PayPalCommerce\Blocks\wc_terms_and_conditions_page_id() 

### ISSUE THREAD

**Issue by orfibous** [woocommerce/woocommerce-paypal-payments#2279]
### Describe the Bug

Fatal crash on update to 2.7.1 undefined function WooCommerce\PayPalCommerce\Blocks\wc_terms_and_conditions_page_id() 

Error log: Uncaught Error: Call to undefined function WooCommerce\PayPalCommerce\Blocks\wc_terms_and_conditions_page_id() in ../wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-blocks/extensions.php:47
Stack trace:
#0 ../wp-content/plugins/woocommerce-paypal-payments/lib/packages/Dhii/Container/CompositeCachingServiceProvider.php(132): WooCommerce\PayPalCommerce\Blocks\BlocksModule->WooCommerce\PayPalCommerce\Blocks\{closure}(Object(WooCommerce\PayPalCommerce\Vendor\Dhii\Container\DelegatingContainer), Array)
#1 ../wp-content/plugins/woocommerce-paypal-payments/lib/packages/Dhii/Container/CompositeCachingServiceProvider.php(131): WooCommerce\PayPalCommerce\Vendor\Dhii\Container\CompositeCachingServiceProvider->WooCommerce\PayPalCommerce\Vendor\Dhii\Container\{closure}(Object(WooCommerce\PayPalCommerce\Vendor\Dhii\Container\DelegatingContainer), Array)
#2 ../wp-content/plugins/woocommerce-paypal-payments/lib/packages/Dhii/Container/CompositeCachingServiceProvider.php(131): WooCommerce\PayPalCommerce\Vendor\Dhii\Container\CompositeCachingServiceProvider->WooCommerce\PayPalCommerce\Vendor\Dhii\Container\{closure}(Object(WooCommerce\PayPalCommerce\Vendor\Dhii\Container\DelegatingContainer), Array)
#3 ../wp-content/plugins/woocommerce-paypal-payments/lib/packages/Dhii/Container/CompositeCachingServiceProvider.php(131): WooCommerce\PayPalCommerce\Vendor\Dhii\Container\CompositeCachingServiceProvider->WooCommerce\PayPalCommerce\Vendor\Dhii\Container\{closure}(Object(WooCommerce\PayPalCommerce\Vendor\Dhii\Container\DelegatingContainer), Array)
#4 ../wp-content/plugins/woocommerce-paypal-payments/lib/packages/Dhii/Container/DelegatingContainer.php(144): WooCommerce\PayPalCommerce\Vendor\Dhii\Container\CompositeCachingServiceProvider->WooCommerce\PayPalCommerce\Vendor\Dhii\Container\{closure}(Object(WooCommerce\PayPalCommerce\Vendor\Dhii\Container\DelegatingContainer), Array)
#5 ../wp-content/plugins/woocommerce-paypal-payments/lib/packages/Dhii/Container/DelegatingContainer.php(74): WooCommerce\PayPalCommerce\Vendor\Dhii\Container\DelegatingContainer->invokeExtension(Object(Closure), Array)
#6 ../wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-wc-gateway/services.php(302): WooCommerce\PayPalCommerce\Vendor\Dhii\Container\DelegatingContainer->get('wcgateway.setti...')
#7 ../wp-content/plugins/woocommerce-paypal-payments/lib/packages/Dhii/Container/DelegatingContainer.php(117): WooCommerce\PayPalCommerce\WcGateway\WCGatewayModule::WooCommerce\PayPalCommerce\WcGateway\{closure}(Object(WooCommerce\PayPalCommerce\Vendor\Dhii\Container\DelegatingContainer))
#8 ../wp-content/plugins/woocommerce-paypal-payments/lib/packages/Dhii/Container/DelegatingContainer.php(56): WooCommerce\PayPalCommerce\Vendor\Dhii\Container\DelegatingContainer->invokeFactory(Object(Closure))
#9 ../wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-wc-gateway/services.php(77): WooCommerce\PayPalCommerce\Vendor\Dhii\Container\DelegatingContainer->get('wcgateway.setti...')
#10 ../wp-content/plugins/woocommerce-paypal-payments/lib/packages/Dhii/Container/DelegatingContainer.php(117): WooCommerce\PayPalCommerce\WcGateway\WCGatewayModule::WooCommerce\PayPalCommerce\WcGateway\{closure}(Object(WooCommerce\PayPalCommerce\Vendor\Dhii\Container\DelegatingContainer))
#11 ../wp-content/plugins/woocommerce-paypal-payments/lib/packages/Dhii/Container/DelegatingContainer.php(56): WooCommerce\PayPalCommerce\Vendor\Dhii\Container\DelegatingContainer->invokeFactory(Object(Closure))
#12 ../wp-content/plugins/woocommerce-paypal-payments/lib/packages/Dhii/Container/CompositeContainer.php(53): WooCommerce\PayPalCommerce\Vendor\Dhii\Container\DelegatingContainer->get('wcgateway.paypa...')
#13 ../wp-content/plugins/woocommerce-paypal-payments/lib/packages/Dhii/Container/CachingContainer.php(61): WooCommerce\PayPalCommerce\Vendor\Dhii\Container\CompositeContainer->get('wcgateway.paypa...')
#14 ../wp-content/plugins/woocommerce-paypal-payments/lib/packages/Dhii/Container/CachingContainer.php(161): WooCommerce\PayPalCommerce\Vendor\Dhii\Container\CachingContainer->WooCommerce\PayPalCommerce\Vendor\Dhii\Container\{closure}()
#15 ../wp-content/plugins/woocommerce-paypal-payments/lib/packages/Dhii/Container/CachingContainer.php(128): WooCommerce\PayPalCommerce\Vendor\Dhii\Container\CachingContainer->invokeGenerator(Object(Closure))
#16 ../wp-content/plugins/woocommerce-paypal-payments/lib/packages/Dhii/Container/CachingContainer.php(60): WooCommerce\PayPalCommerce\Vendor\Dhii\Container\CachingContainer->getCached('wcgateway.paypa...', Object(Closure))
#17 ../wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-wc-gateway/src/WCGatewayModule.php(510): WooCommerce\PayPalCommerce\Vendor\Dhii\Container\CachingContainer->get('wcgateway.paypa...')
#18 ../wp-includes/class-wp-hook.php(324): WooCommerce\PayPalCommerce\WcGateway\WCGatewayModule::WooCommerce\PayPalCommerce\WcGateway\{closure}(Array)
#19 ../wp-includes/plugin.php(205): WP_Hook->apply_filters(Array, Array)
#20 ../wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(94): apply_filters('woocommerce_pay...', Array)
#21 ../wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(76): WC_Payment_Gateways->init()
#22 ../wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(49): WC_Payment_Gateways->__construct()
#23 ../wp-content/plugins/cardlink-payment-gateway/includes/class-cardlink-payment-gateway-ajax.php(24): WC_Payment_Gateways::instance()
#24 ../wp-content/plugins/cardlink-payment-gateway/includes/class-cardlink-payment-gateway-ajax.php(9): Cardlink_Payment_Gateway_Delete->__construct()
#25 ../wp-includes/class-wp-hook.php(324): Cardlink_Payment_Gateway_Delete::get_instance('')
#26 ../wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#27 ../wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#28 ../wp-settings.php(673): do_action('after_setup_the...')
#29 ../wp-config.php(105): require_once('/var/www/f5b4ec...')
#30 ../wp-load.php(50): require_once('/var/www/f5b4ec...')
#31 ../wp-admin/admin.php(34): require_once('/var/www/f5b4ec...')
#32 ../wp-admin/plugins.php(10): require_once('/var/www/f5b4ec...')
#33 {main}
thrown

### To Reproduce

1. Update plugin to 2.7.1
2. Site crashes

### Expected Behavior

No fatal crash.

### Actual Behavior

Fatal crash on the whole site.

### Environment

 - WordPress 6.5.3
 - WooCommerce  8.9.1
 - Plugin Version 2.7.1
 - All Browsers
 - Many plugins installed but seem unrelated to this.

**Comment by InpsydeNiklas** [comment]
Hi @orfibous, can you please [contact the support team directly form here](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) with a copy of your WooCommerce system report and a link to this issue? Errors like this could potentially happen when navigating the site during a plugin update, but should be resolved once the update was completed. Thanks!

**Comment by orfibous** [comment]
Hi @InpsydeNiklas , The problem still remains. We have disabled the plugin for now. We also sent the support ticket!

**Comment by orfibous** [comment]
The issue was caused by a conflict with another plugin.

**Comment by robindarlington** [comment]
This suddenly showed up on my website today. Can you please say which other plugin, in case it may help me or others out?

PHP Fatal error:  Uncaught Error: Call to undefined function WooCommerce\PayPalCommerce\Blocks\wc_terms_and_conditions_page_id() in /srv/data/web/vhosts/belair.bio/htdocs/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-blocks/extensions.php:47

**Comment by orfibous** [comment]
> This suddenly showed up on my website today. Can you please say which other plugin, in case it may help me or others out?
> 
> PHP Fatal error: Uncaught Error: Call to undefined function WooCommerce\PayPalCommerce\Blocks\wc_terms_and_conditions_page_id() in /srv/data/web/vhosts/belair.bio/htdocs/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-blocks/extensions.php:47

Hi @robindarlington it was caused by Cardlink checkout Payment Gateway for WooCommerce,, a plugin mainly targeting the Greek market. Your problem could be caused by some other payment plugin.

**Comment by dilankafernando** [comment]
@orfibous  I encountered the same issue, which was due to a conflict between "Woopayments" and "WooCommerce PayPal Payments." I resolved it by removing "Woopayments" since I didn't use it, and then it worked.

**Comment by AaronNewcomer** [comment]
y'all introduced this bug again!? Disabling WooPayments also fixed it for me. Thanks @dilankafernando !

**Comment by CobaltBlueDW** [comment]
Disabling PayPalCommerce fixed this bug for me.

**Comment by julinedossantos** [comment]
Appeared again here: 8556233-zen  and here: 8556064-zen
