### ISSUE TITLE
Frequent error "Unprocessable entity" since update to v1.8.1

### ISSUE THREAD

**Issue by tritos-design** [woocommerce/woocommerce-paypal-payments#687]
### Describe the Bug

I am experiencing quite frequent errors since the update to the plugin version 1.8.1

Example from the logs:

2022-06-18T20:32:36+00:00 DEBUG POST https://api.paypal.com/v2/checkout/orders/...../capture
Response Debug ID: b33daf6e828bf
Response: Array
(
    [code] => 422
    [message] => Unprocessable Entity
)

The customers seem to get an error message and on the second try the payment seems to work most of the time. Is this a known issue? I haven't seen any such errors for weeks, but since the update to v1.8.1 about 50% of the payments fail at the first try.

### Expected Behavior

Payment works.

### Actual Behavior
Payment fails at first try.

### Environment

 - WordPress Version 6.0
 - WooCommerce Version 6.5.1
 - Plugin Version 1.8.1
 - not dependent on Browser
 - Any other plugins installed: Germanized forWooCommerce 3.9.4 and Germanized for WooCommerce Pro 3.5.3

**Comment by InpsydeNiklas** [comment]
Could you please open a support ticket from here? https://paypal.inpsyde.com/docs/request-support/
Please include a link to this issue as we a re not aware of other reports of this kind.
It may also be worthwhile to reach out to the PayPal MTS with a copy of the logfile.
Thanks!

**Comment by nelsonandrea95** [comment]
I'm facing the same issue on my website, I'm using WooCommerce PayPal Payments 1.8.1

**Comment by tritos-design** [comment]
> Could you please open a support ticket from here? https://paypal.inpsyde.com/docs/request-support/ Please include a link to this issue as we a re not aware of other reports of this kind. It may also be worthwhile to reach out to the PayPal MTS with a copy of the logfile. Thanks!

I opened a support ticket at https://paypal.inpsyde.com/docs/request-support/

**Comment by webtech-tom** [comment]
I'm facing the same issue. I'm using WooCommerce PayPal Payments Version 1.9.2.

**Comment by Tonuz** [comment]
Same here

**Comment by AfterHAL** [comment]
Hi there. Same for me since 1.9.2 
and same issue on 1.9.3.
Also, the customer's bank account is debited by the order amount , and then credited of the same amount a couple of seconds after...

**Comment by Sirvijver** [comment]
Hello all,

as you see, we don't provide plugin support via GitHub, so we would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance. This ticket will be closed because of this reason.

The issue that was raised here, is most likely already resolved in our current release, so please verify the issue is still present if you update all the plugins on your website before engaging us. Thank you.

Kind regards, 
Joost

**Comment by Brahimo1994** [comment]
Here's a polished version of your comment:

Hello,

The issue persists, and over 60% of my clients are still encountering this error. I've reached out to PayPal's tech support team, who confirmed that the issue isn’t on their end. I also contacted PayPal account support and received the same response. This remains unresolved.

Thank you.
